
CREATE TABLE `persons` (
`Id` INT (10) UNSIGNED NULL DEFAULT NULL,
`PrimeiroNome` VARCHAR (50) NULL DEFAULT NULL,
`SegundoNome` VARCHAR (50) NULL DEFAULT NULL,
`Endereco` VARCHAR (50) NULL DEFAULT NULL,
`Genero` VARCHAR (50) NULL DEFAULT NULL
)
ENGINE = InnoDB
;